import { WHITE_LIST_APPLICATION_STATUSES } from './WHITE_LIST_APPLICATION_STATUSES';

export const STATUSES_COLOR = {
    [WHITE_LIST_APPLICATION_STATUSES.NEW]: '#ffb94b',
    [WHITE_LIST_APPLICATION_STATUSES.RED]: '#672e2f',
    [WHITE_LIST_APPLICATION_STATUSES.WHITE]: '#fff',
    [WHITE_LIST_APPLICATION_STATUSES.BOOKED]: '#00c681',
    [WHITE_LIST_APPLICATION_STATUSES.MINTED]: '#0082df',
    [WHITE_LIST_APPLICATION_STATUSES.DELETED]: '#b63234',
};
